twig:
    debug: '%kernel.debug%'
    default_path: '%kernel.project_dir%/templates'
    strict_variables: '%kernel.debug%'
    exception_controller: null

    globals:
        site_url: "https://getrector.org"
        main_page_title: "Rector - Automated Way to Instantly Upgrade and Refactor any PHP code"

        # see https://symfony.com/doc/current/templating/global_variables.html#referencing-services
        rector_count_provider: '@Rector\Website\Twig\RectorCountVariableProvider'

        # @todo create this
        disqus_name: "getrectororg"

    # see https://symfony.com/blog/new-in-symfony-2-7-default-date-and-number-format-configuration
    date:
        format: 'j. n., G:i' # Czech format

    # see https://symfony.com/blog/new-in-symfony-2-7-default-date-and-number-format-configuration
    number_format:
        decimals: 0
        decimal_point: ','
        thousands_separator: ' '
