name: Deploy

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: chrnorm/deployment-action@releases/v1
              name: Create GitHub deployment
              id: github_deploy
              with:
                initial_status: "in_progress"
                token: "${{ github.token }}"
                environment: prod

            - uses: actions/checkout@v2

            - name: Log into registry
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Build and push image
              run: |
                docker build . --tag rector/getrector.com:latest --build-arg commitHash=${{ github.sha }}
                docker push rector/getrector.org:latest

            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USERNAME }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  script: "cd /projects/getrector.org && ./run.sh"

            - name: Update GitHub deployment status (success)
              if: success()
              uses: chrnorm/deployment-status@releases/v1
              with:
                token: "${{ github.token }}"
                state: "success"
                deployment_id: ${{ steps.github_deploy.outputs.deployment_id }}

            - name: Update GitHub deployment status (failure)
              if: failure()
              uses: chrnorm/deployment-status@releases/v1
              with:
                token: "${{ github.token }}"
                state: "failure"
                deployment_id: ${{ steps.github_deploy.outputs.deployment_id }}
