name: Production build

on:
    push: null
    schedule:
        # https://crontab.guru/daily
        -   cron: "0 0 * * *"

jobs:
    production_build:
        name: Porduction Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                php-version: 8.0

            - run: composer update

            - uses: stefanzweifel/git-auto-commit-action@v2.3.0
              with:
                commit_message: Apply automatic update
                branch: ${{ github.head_ref }}
              env:
                GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

            - name: Build image
              run: |
                docker build . --tag image --build-arg commitHash=${{ github.sha }}

            - name: Warmup cache
              run: docker run -e APP_ENV=prod image bin/console cache:warmup

            - name: Doctrine schema validation
              run: docker run -e APP_ENV=prod image bin/console doctrine:schema:validate --skip-sync --ansi
